/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSwileRouteImport } from './routes/_app.swile'
import { Route as AppOrcamentoBaseRouteImport } from './routes/_app.orcamento-base'
import { Route as AppGerarMesRouteImport } from './routes/_app.gerar-mes'
import { Route as AppFundosRouteImport } from './routes/_app.fundos'
import { Route as AppExecutarRouteImport } from './routes/_app.executar'
import { Route as AppExcecoesRouteImport } from './routes/_app.excecoes'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCartoesRouteImport } from './routes/_app.cartoes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSwileRoute = AppSwileRouteImport.update({
  id: '/swile',
  path: '/swile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentoBaseRoute = AppOrcamentoBaseRouteImport.update({
  id: '/orcamento-base',
  path: '/orcamento-base',
  getParentRoute: () => AppRoute,
} as any)
const AppGerarMesRoute = AppGerarMesRouteImport.update({
  id: '/gerar-mes',
  path: '/gerar-mes',
  getParentRoute: () => AppRoute,
} as any)
const AppFundosRoute = AppFundosRouteImport.update({
  id: '/fundos',
  path: '/fundos',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutarRoute = AppExecutarRouteImport.update({
  id: '/executar',
  path: '/executar',
  getParentRoute: () => AppRoute,
} as any)
const AppExcecoesRoute = AppExcecoesRouteImport.update({
  id: '/excecoes',
  path: '/excecoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesRoute = AppCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cartoes': typeof AppCartoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/excecoes': typeof AppExcecoesRoute
  '/executar': typeof AppExecutarRoute
  '/fundos': typeof AppFundosRoute
  '/gerar-mes': typeof AppGerarMesRoute
  '/orcamento-base': typeof AppOrcamentoBaseRoute
  '/swile': typeof AppSwileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cartoes': typeof AppCartoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/excecoes': typeof AppExcecoesRoute
  '/executar': typeof AppExecutarRoute
  '/fundos': typeof AppFundosRoute
  '/gerar-mes': typeof AppGerarMesRoute
  '/orcamento-base': typeof AppOrcamentoBaseRoute
  '/swile': typeof AppSwileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/cartoes': typeof AppCartoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/excecoes': typeof AppExcecoesRoute
  '/_app/executar': typeof AppExecutarRoute
  '/_app/fundos': typeof AppFundosRoute
  '/_app/gerar-mes': typeof AppGerarMesRoute
  '/_app/orcamento-base': typeof AppOrcamentoBaseRoute
  '/_app/swile': typeof AppSwileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cartoes'
    | '/dashboard'
    | '/excecoes'
    | '/executar'
    | '/fundos'
    | '/gerar-mes'
    | '/orcamento-base'
    | '/swile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cartoes'
    | '/dashboard'
    | '/excecoes'
    | '/executar'
    | '/fundos'
    | '/gerar-mes'
    | '/orcamento-base'
    | '/swile'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/cartoes'
    | '/_app/dashboard'
    | '/_app/excecoes'
    | '/_app/executar'
    | '/_app/fundos'
    | '/_app/gerar-mes'
    | '/_app/orcamento-base'
    | '/_app/swile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/swile': {
      id: '/_app/swile'
      path: '/swile'
      fullPath: '/swile'
      preLoaderRoute: typeof AppSwileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamento-base': {
      id: '/_app/orcamento-base'
      path: '/orcamento-base'
      fullPath: '/orcamento-base'
      preLoaderRoute: typeof AppOrcamentoBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gerar-mes': {
      id: '/_app/gerar-mes'
      path: '/gerar-mes'
      fullPath: '/gerar-mes'
      preLoaderRoute: typeof AppGerarMesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fundos': {
      id: '/_app/fundos'
      path: '/fundos'
      fullPath: '/fundos'
      preLoaderRoute: typeof AppFundosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/executar': {
      id: '/_app/executar'
      path: '/executar'
      fullPath: '/executar'
      preLoaderRoute: typeof AppExecutarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/excecoes': {
      id: '/_app/excecoes'
      path: '/excecoes'
      fullPath: '/excecoes'
      preLoaderRoute: typeof AppExcecoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes': {
      id: '/_app/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof AppCartoesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCartoesRoute: typeof AppCartoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExcecoesRoute: typeof AppExcecoesRoute
  AppExecutarRoute: typeof AppExecutarRoute
  AppFundosRoute: typeof AppFundosRoute
  AppGerarMesRoute: typeof AppGerarMesRoute
  AppOrcamentoBaseRoute: typeof AppOrcamentoBaseRoute
  AppSwileRoute: typeof AppSwileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCartoesRoute: AppCartoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExcecoesRoute: AppExcecoesRoute,
  AppExecutarRoute: AppExecutarRoute,
  AppFundosRoute: AppFundosRoute,
  AppGerarMesRoute: AppGerarMesRoute,
  AppOrcamentoBaseRoute: AppOrcamentoBaseRoute,
  AppSwileRoute: AppSwileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
